Align miniqmc_sync_move option and fix unit test
QMCPACK/miniqmc pull request #246
Opened 2019-06-13 00:16 UTC by ye-luo

2019-06-13 14:48 UTC, ye-luo commented
Test this please

2019-06-14 20:34 UTC, PDoakORNL requested changes
I changed this option to -c in MiniQMCOptions in #244 which is more mnenomic with crowd. It would also be great if we could start using that class, this local scope argument parsing bloats this file and is not compatible with concurrency methods the don't hand the entire block scope to every thread.

2019-06-14 20:41 UTC, ye-luo commented
I didn't notice that you changed -p to -c. We should align. Give me a second.
Yes. it will be connected to MiniQMCOptions. The change will not be small and I need to a a separate PR.

2019-06-14 21:22 UTC, PDoakORNL approved these changes

2019-06-14 21:27 UTC, merged